version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace
      - ~/.gitconfig:/root/.gitconfig
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    command: sleep infinity
